### ISSUE TITLE
NoGapHandler is not available in latest version

### ISSUE THREAD

**Issue by losimons** [predict-idlab/plotly-resampler#221] opened 2023-05-31 09:23 UTC
I am currently using the latest version of plotly_resampler and wanted to make use of the NoGapHandler property to color the background of my plot. However, I am not able to import the NoGapHandler from the plotly_resampler.aggregation module. Is it not yet available in the latest version?

Specifics about the version I am using: 

Name: plotly-resampler
Version: 0.8.3.2
Summary: Visualizing large time series with plotly
Home-page: https://github.com/predict-idlab/plotly-resampler
Author: Jonas Van Der Donckt
Author-email: 
License: MIT
Location: /Users/loresimons/miniconda3/envs/epicare-annotator/lib/python3.8/site-packages
Requires: dash, jupyter-dash, numpy, orjson, pandas, plotly, trace-updater
Required-by:

**Comment by jvdd** [comment] 2023-05-31 11:23
Hi @losimons,

This new feature / functionality will be provided in the next major release (`v.0.9.0`). However, you can already install the latest pre-release (that includes this functionality; https://pypi.org/project/plotly-resampler/0.9.0rc5/

The underlying issue / confusion is caused by plotly-resampler not having versioned docs :smiling_face_with_tear: 

Hope this answer helps!

Cheers,
Jeroen

**Comment by jonasvdd** [comment] 2023-05-31 11:38
Hey @losimons,

The documentation is generated from the master branch, which means it reflects the latest version. Currently, we are working on a major update to the toolkit that includes improvements such as 2-3 times faster back-end resampling and the refactoring of certain functionalities such as gap handling. As a result, we are using release candidates (rc's) and expect some bugs to occur. We also plan to generate documentation for each major code versioning the near future.

**fyi**: you can find the release history (of these release candidates in which the gaphandlers are included) [here](https://pypi.org/project/plotly-resampler/#history).

I see that you are from byte flies and working on an annotator dashboard.
Currently, I am brainstorming some future papers about data annotation dashboards for healthcare applications ([conference link current year](https://visualanalyticshealthcare.github.io/homepage/2023/call-for-papers.html)) (mostly applied to longitudinal sensor data; i.e. the [mBrain](https://link.springer.com/article/10.1186/s12911-022-01813-w)) study. Hence, I think it would be fascinating to hear your use cases and examples (in a meeting over the summer (in Dutch 😛)).

<3 Open source,
Jonas

**Comment by losimons** [comment] 2023-06-02 06:41
Hi Jonas, 

Thanks for the response! Will use the pre-release version then!

And always in for a chat. If you can provide me your email, I will send you some timeslots to plan in an introduction (during summer, in Dutch ;-) ).

Kind regards, 
Lore

**Comment by jonasvdd** [comment] 2023-07-13 07:10
@losimons,

fyi: 
- As of now, we have versioned docs. 🥳 - go check them out via [this link](https://predict-idlab.github.io/plotly-resampler/v0.9.0/)
- Furthermore, `plotly-resampler` 0.9.0 leverages our `tsdownsample` package, which improves the aggregation performance! 🐎 

I Will close this issue for now, but we will put a reminder in my calendar to re-contact you for this meeting.

**Closed by jonasvdd** 2023-07-13 07:10 UTC
Labels: documentation
