### ISSUE TITLE
Pandas 2.0.0 dependency conflict

### ISSUE THREAD

**Issue by florian6973** [predict-idlab/plotly-resampler#203] opened 2023-04-26 12:49 UTC
Hi!

I would like to install plotly-resampler 0.8.3.2 but it fails because other libraries are using pandas 2.0.x

Will a fix be released soon in plotly-resampler to support pandas 2.0.0 please?

Thanks

**Comment by jvdd** [comment] 2023-04-26 12:55
Hey @florian6973 

You can try installing [pre-release `0.9.0rc0`](https://pypi.org/project/plotly-resampler/0.9.0rc0/), which should allow using pandas 2.0 :)

In a couple of weeks we plan to do a new major release (0.9.0) where pandas 2.0 is allowed - in the meantime this release candidate (`0.9.0rc0`) should help you out.

Hope this helps!

---

Duplicate of #193

**Comment by anirban-ray-publicis-sapient** [comment] 2023-07-12 07:48
Hi @jvdd, can you share any possible ETA for 0.9.0 release? We are using `plotly-resampler` indirectly as a dependency of `statsforecast`, and will really prefer to start using `pandas` v2 now, especially because few of our other dependencies.

**Comment by jonasvdd** [comment] 2023-07-12 09:56
Hi @anirban-ray-publicis-sapient, V0.9.0 is released! 🚀

**Comment by jonasvdd** [comment] 2023-07-12 09:56
If you can confirm that this works as expected, we can close this issue! :)

**Comment by anirban-ray-publicis-sapient** [comment] 2023-07-12 10:26
Hi @jonasvdd, I can confirm that my problem is solved. Thanks a lot for the super prompt response.

**Closed** 2023-07-12 11:25 UTC
