### ISSUE TITLE
Attribute Error when running examples 

### ISSUE THREAD

**Issue by andersdot** [predict-idlab/plotly-resampler#23] opened 2022-02-02 01:05 UTC
When running your example notebook I get the following error:

`AttributeError: ('Read-only: can only be set in the Dash constructor or during init_app()', 'requests_pathname_prefix')`

Maybe it's a plotly version issue?

Cheers

**Comment by jonasvdd** [comment] 2022-02-02 11:27
Hi @andersdot,

Thank you for submitting this issue,
I am able to reproduce it, I'm on it 🔍 !
Keep you posted!

**Comment by jonasvdd** [comment] 2022-02-02 13:24
The problem is indeed with the dash version. The current `JupyterDash` version is not compatible with `Dash` v2.1.0 (see: https://github.com/plotly/jupyter-dash/issues/75). 
It is their responsibility to resolve this.

As for now, I will fixate the dash version in the pyproject.toml to v2.0.0 as hotfix.
Once `JupyterDash` has resolved this issue, I can release this lock.

**Comment by jonasvdd** [comment] 2022-02-02 13:53
@jvdd, I suppose we create a new release as the tests have run successfully?

**Comment by jvdd** [comment] 2022-02-03 09:27
Published a new release with this hotfix!

Thx for pointing out the issue @andersdot :)

**Comment by jonasvdd** [comment] 2022-03-02 10:57
New version released, I will close this issue

**Closed by jonasvdd** 2022-03-02 10:57 UTC
Labels: bug, Hotfixed
