### ISSUE TITLE
Question: does it work with large 2D-heatmaps?

### ISSUE THREAD

**Issue by sorenwacker** [predict-idlab/plotly-resampler#71] opened 2022-06-11 03:12 UTC
I wonder if `plotly-resampler` works primarily with timelines or can be applied to large two dimensional heatmaps or histograms.

**Comment by jvdd** [comment] 2022-06-11 07:45
Hey @sorenwacker,

At the moment, `plotly-resampler` works only for scatter / line plots (i.e., 1D resampling). However, I'm open to extending the code base to also support 2D resampling (but I myself won't find the time for this is the near future).

This is a duplicate of #59 (which we apparently left unanswered - sorry for that...).

I will close this duplicate and repeat this answer in issue #59!

Cheers,
Jeroen

**Closed by jvdd** 2022-06-11 07:45 UTC

**Comment by jvdd** [comment] 2026-08-31 18:23
Hi @sorenwacker, this is now supported by [FlexViz](https://github.com/flex-analytics/flexviz)

FlexViz (our successor library to plotly-resampler) supports large 2D heatmaps through viewport-aware Histogram2D aggregation. It bins the source columns on demand and sends only the bounded grid needed by the current view.

It also supports geographic 2D histograms, and comes natively with cross-filtering + linked hover, and scales out of core. The source data stays in Polars on the server, so (similar to plotly-resampler) the browser does not need to receive the full dataset.

This issue appears to be a duplicate of [#59](https://github.com/predict-idlab/plotly-resampler/issues/59), but I wanted to share that the requested functionality is now available in FlexViz :)
