### ISSUE TITLE
Windows: Could not import lttbc

### ISSUE THREAD

**Issue by Jeremy38100** [predict-idlab/plotly-resampler#180] opened 2023-03-30 09:14 UTC
Hello,

I'm developping a dash application for dataviz.
It's working well on MacOS but i'm trying to run this app on a Windows 11 environement.
pip install works well without any messages but when I run my app I have the following warning :

```
[...]venv\lib\site-packages\plotly_resampler\aggregation\aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
  warnings.warn("Could not import lttbc; will use a (slower) python alternative.")
```

Also it's raising this warning :
```
[...]venv\lib\site-packages\plotly_resampler\aggregation\algorithms\lttb_py.py:34: RuntimeWarning:
overflow encountered in scalar multiply
```

I assume the slower python alternative is VERY slow and it's kinda blocking.

I tried to install manually lttbc manually with `pip install lttbc` and run the example from the documentation https://pypi.org/project/lttbc/

The example script works well but I still have same warnings when i run my dash app

**Comment by jvdd** [comment] 2023-03-30 09:31
Hi @Jeremy38100,

It appears that the lttb `C` code could not be compiled on the Windows machine (most likely due to missing `gcc` or other `C` compiling requirements).

As a fast alternative to the `lttbc`, you could for example opt to use the [`MinMax`](https://predict-idlab.github.io/plotly-resampler/aggregation.html#plotly_resampler.aggregation.aggregators.MinMaxAggregator) aggregator! :) 

The overflow error seems to be a bug. If you can provide some reproducible code, I'll gladly have a look at it :)

Cheers, Jeroen

---

P.S.: In the near future, we will remove the `C` code from this library and use [tsdownsample](https://github.com/predict-idlab/tsdownsample ) compiled `Rust` code instead.
=> this should further increase the downsampling performance (up to 10x), while having no burden on the end-user to compile code on his/her machine.

**Comment by Jeremy38100** [comment] 2023-03-30 10:36
@jvdd  Thanks for your answer, I will provide you a reproductible code for the overflow error.

I did not figured out how to use the MinMax aggregator with my current code base. Is it possible to provide an example of how to use it, I can not find one in the examples files.

Thanks, Jeremy

**Comment by jvdd** [comment] 2023-03-30 10:56
@Jeremy38100 

Here is an illustration of how you can manually set the downsampler :arrow_down: 

```py
from plotly_resampler import FigureResampler
from plotly_resampler.aggregation import MinMaxAggregator

fig = FigureResampler(default_downsampler=MinMaxAggregator(), default_n_shown_samples=1500)
# add some data
# ...
```

See more details in [`FigureResampler` docs](https://predict-idlab.github.io/plotly-resampler/figure_resampler.html#plotly_resampler.figure_resampler.FigureResampler)

Hope this helps!

**Comment by Jeremy38100** [comment] 2023-03-30 16:55
@jvdd Here is an example of a codebase where I tried to covered multiple cases.

With the `fig: FigureResampler = FigureResampler()` line here are my console output :
```
viewer\venv\lib\site-packages\plotly_resampler\aggregation\aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
  warnings.warn("Could not import lttbc; will use a (slower) python alternative.")
Dash is running on http://127.0.0.1:9023/

 * Serving Flask app 'test'
 * Debug mode: on
viewer\venv\lib\site-packages\plotly_resampler\aggregation\aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
  warnings.warn("Could not import lttbc; will use a (slower) python alternative.")
Add trace with unix epoch format
viewer\venv\lib\site-packages\plotly_resampler\aggregation\algorithms\lttb_py.py:34: RuntimeWarning:

overflow encountered in scalar multiply

3024000 points:  52.86 ms
Add trace with pd.to_datetime format
viewer\venv\lib\site-packages\plotly_resampler\aggregation\algorithms\lttb_py.py:34: RuntimeWarning:

overflow encountered in scalar multiply

3024000 points:  715.95 ms
```

You can find the code below.
Also as you can see I noticed that plot a timeserie with unix epoch timestamp instead of a panda datetime is way more faster (
~14x faster). Is it a bug ? Is it possible to plot with the unix epoch and transform tick label on x axis and hover tooltip to print datetime in string format?

``` python
import numpy as np
import plotly.graph_objects as go
from dash import Dash, Input, Output, callback_context, dcc, html, no_update
from trace_updater import TraceUpdater
import pandas as pd
import time
from plotly.subplots import make_subplots
from plotly_resampler import FigureResampler
from plotly_resampler.aggregation import MinMaxAggregator


app = Dash(__name__)

# With thisfollowing line both warnings are triggered:
#
# plotly_resampler\aggregation\aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
#   warnings.warn("Could not import lttbc; will use a (slower) python alternative.")
#
# plotly_resampler\aggregation\algorithms\lttb_py.py:34: RuntimeWarning:
#      overflow encountered in scalar multiply
# -------------
fig: FigureResampler = FigureResampler()

# With thisfollowing line code only one warning is triggered:
#
# plotly_resampler\aggregation\aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
#   warnings.warn("Could not import lttbc; will use a (slower) python alternative.")
# -------------
# fig: FigureResampler = FigureResampler(default_downsampler=MinMaxAggregator(), default_n_shown_samples=1500)

app.layout = html.Div(
    [
        html.H1("plotly-resampler global variable", style={"textAlign": "center"}),
        html.Button("plot chart", id="plot-button", n_clicks=0),
        html.Hr(),
        dcc.Graph(id="graph-id"),
        TraceUpdater(id="trace-updater", gdID="graph-id"),
    ]
)

@app.callback(
    Output("graph-id", "figure"),
    Input("plot-button", "n_clicks"),
    prevent_initial_call=True,
)
def plot_graph(n_clicks):
    ctx = callback_context
    if len(ctx.triggered) and "plot-button" in ctx.triggered[0]["prop_id"]:
        global fig
        fig.replace(go.Figure(
            make_subplots( rows=2,cols=1)
        ))

        #Genrate a dataframe with following structure:
        #         dt_epoch              x                      dt
        # 0  1680193943000  1680193943000 2023-03-30 16:32:23.000
        # 1  1680193943200  1680193943200 2023-03-30 16:32:23.200
        # 2  1680193943400  1680193943400 2023-03-30 16:32:23.400
        # 3  1680193943600  1680193943600 2023-03-30 16:32:23.600
        # 4  1680193943800  1680193943800 2023-03-30 16:32:23.800

        start = 1680193943000
        end = start + 1000 * 60 * 60 * 24 * 7 # 7 days later
        step = 200
        df = pd.DataFrame({'dt_epoch': np.arange(start, end, step)})
        # set sensor value to date for example
        df['x'] = df[['dt_epoch']]
        # convert epoch to datetime in order to have a correct date displayed in xaxes and hover tooltip
        df['dt'] = pd.to_datetime(df['dt_epoch'], unit='ms')

        # Insert timeserie with unix epoch datetime
        print('Add trace with unix epoch format')
        start_time = time.time()
        fig.add_trace(go.Scattergl(name="log", x=df['dt_epoch'], y=df['x']), row=1, col=1)
        end_time = time.time()
        execution_time = (end_time - start_time) * 1000
        print(len(df["x"]), "points: " , f"{execution_time:.2f} ms")

        # Insert timeserie with pd.to_datetime datetime
        print('Add trace with pd.to_datetime format')
        start_time = time.time()
        fig.add_trace(go.Scattergl(name="log", x=df['dt'], y=df['x']), row=2, col=1)
        end_time = time.time()
        execution_time = (end_time - start_time) * 1000
        print(len(df["x"]), "points: " , f"{execution_time:.2f} ms")

        return fig
    else:
        return no_update


fig.register_update_graph_callback(
    app=app, graph_id="graph-id", trace_updater_id="trace-updater"
)

if __name__ == "__main__":
    app.run_server(debug=True, port=9023)

```

**Comment by jvdd** [comment] 2023-04-03 18:12
Hey @Jeremy38100,

Appreciate the clear & reproducible code :handshake: 

When running your code above I noticed (on my machine) that the pandas datetime was 25x slower than the unix epoch timestamp :exploding_head: 
This made me remember a previous related issue #120, which was tackled in #120 

Long story short - plotly is **EXTREMELY** slow when it comes to serializing object arrays (which is the internal representation they use for pandas datetime). Illustration below :arrow_down: 
When adding to scattergl
![image](https://user-images.githubusercontent.com/18898740/229591327-8cf79030-23cd-45d4-9e2a-ccfd7cdea346.png)
When adding to figure
![image](https://user-images.githubusercontent.com/18898740/229587185-12fafec0-d912-43f8-9ab0-94f94ff20444.png)

As such, the overhead you are noticing does not stem from the downsampling, but rather form the serializing (which is more a plotly.py issue - you can always submit an issue over there).

So far the bad news, now time for the good news! You can easily overcome this issue :slightly_smiling_face: 
In the end, you want to pass the data to the plotly-resampler figure - and not to the scatter. Since we were already aware of this (in general) unnecessary overhead when adding data to a plotly scatter, you can add an empty scatter and add your data as `hf_x` and `hf_y` arguments - resulting in (automatically - under the hood) only adding the downsampled data to the scatter (instead of trying to add all data) :tada: 
See example below :arrow_down: 

```py
# your old code - add data to scatter via x and y arguments
# fig.add_trace(go.Scattergl(name="log", x=df['dt_epoch'], y=df['x']), row=1, col=1)
# overhead-free code - add data to figure without adding it to scatter
fig.add_trace(go.Scattergl(name="log"), hf_x=df['dt_epoch'], hf_y=df['x'], row=1, col=1)
```

=> now there are no / minor differences between epoch & datetime :fire: 
![image](https://user-images.githubusercontent.com/18898740/229592363-d7369600-8d05-4c39-a008-7649d6016dc2.png)

I'll add this to the FAQ of our docs!

Cheers, Jeroen

**Comment by jvdd** [comment] 2023-04-03 19:29
FYI, some other illustration that I included in the FAQ docs in #184 

![image](https://user-images.githubusercontent.com/18898740/229607974-b90332b0-4319-4bdc-abf1-e588d3bcfb5c.png)

**Comment by Jeremy38100** [comment] 2023-04-06 09:11
Awesome!

Thank you for your explanation 👌

**Comment by jonasvdd** [comment] 2023-07-26 19:07
I will close this issue as `plotly-resampler==0.9.0` resolves this.

**Closed by jonasvdd** 2023-07-26 19:07 UTC
Labels: bug, discussion
