### ISSUE TITLE
Error with graph whan a column has a boolean with always same value

### ISSUE THREAD

**Issue by bwatt-fr** [predict-idlab/plotly-resampler#171] opened 2023-02-14 09:38 UTC
Hi,
we encounter an error when trying to draw a plot with a boolean column whith always the same value (True or False).
It appears when showing the mean aggregation size.
When doing this, this line (https://github.com/predict-idlab/plotly-resampler/blob/39072f55409a12c7955cd977659c048cb28865c2/plotly_resampler/figure_resampler/figure_resampler_interface.py#L307) always return 0, because you use np.diff
By consequence, this following line (https://github.com/predict-idlab/plotly-resampler/blob/39072f55409a12c7955cd977659c048cb28865c2/plotly_resampler/figure_resampler/utils.py#L171) is doing a math.log10 on 0, and we encounter a math domain error (because log(0) is impossible).

We are bypassing this by desactivating the show of mean aggregation size (for all our graphes), but we love this feature, so if you could find a workaround it would be great! Just let me know, so I can tell to my users if this number will come back or no. And thanks for your great work!

**Comment by jonasvdd** [comment] 2023-02-14 10:21
Hi @bwatt-fr,

Glad to hear that you are loving our toolkit! 🤗 
Regarding your issue; 
- I find it hard to believe that it has to do with the `dtype` of series its values that you are aggregating; as the `np.diff` is performed on the series its index.

So my questions to you are; 
* what is the index of that series? 
* Do all series items have the same index value; thus all yielding a 0 `np.diff` -> and 0 mean? 

I certainly believe that we should handle the `agg_mean == 0` usecase; so I will look further into it!
Thanks for submitting this issue to us! 👍🏼 

Looking forward to your response,
Jonas

**Comment by bwatt-fr** [comment] 2023-02-14 14:07
Hi,
thanks for answering so fast.

Here the index we use is always True (it's an array filled with True value). We have a system with tons of variables, and you can chose to see one variable depending on another one. And some of these variables are boolean, that's why we have this kind of index (in this case it's not very interesting to visualize, but the user can know that there is only one value for this variable).

It's not a very common use case, that's why I think you never met this bug (in general you visualize with an index with more tahn one value, so you np.diff never give you 0).

**Comment by jvdd** [comment] 2023-02-14 14:52
Hi @bwatt-fr,

This sounds indeed like a rather niche - but still interesting - use-case. 

If you can share a minimal code example, we will gladly have a further look at it :)

Cheers,
Jeroen

**Comment by jvdd** [comment] 2023-02-24 09:40
Thx for the reproducible code @bwatt-fr!

I took a look at the problem and submitted a fix for this bug in #172
I'll let you know when we create a new release containing this fix! :)

Your example code now works and produces this figure :arrow_down: 

![image](https://user-images.githubusercontent.com/18898740/221142611-17a55e73-1c96-4603-bc2c-12cbc6288f40.png)

**Closed** 2023-02-24 12:58 UTC
Labels: bug

**Comment by jvdd** [comment] 2023-03-08 16:17
@bwatt-fr plotly-resampler release `v0.8.3.2` contains now the fix for this bug :)

**Comment by maxime-jolliet-airseas** [comment] 2023-03-27 15:11
Hi,

Thank you for the quick fix!
I tried to test it out, but I have an other problem while running the code snippet of https://github.com/predict-idlab/plotly-resampler/issues/171#issuecomment-1437208547
```
aceback (most recent call last):
  File "/home/jolliet/git/graph/scripts/plotlyresampler.py", line 26, in <module>
    figure.add_trace(
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/figure_resampler/figure_resampler_interface.py", line 1011, in add_trace
    trace = self._check_update_trace_data(trace)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/figure_resampler/figure_resampler_interface.py", line 290, in _check_update_trace_data
    s_res: pd.Series = downsampler.aggregate(
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregation_interface.py", line 157, in aggregate
    s = self._aggregate(s, n_out=n_out)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregators.py", line 295, in _aggregate
    return self.lttb._aggregate(s, n_out)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregators.py", line 90, in _aggregate
    index = LTTB_core.downsample(s_i, s_v, n_out)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/algorithms/lttb_py.py", line 89, in downsample
    LTTB_core_py._argmax_area(
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/algorithms/lttb_py.py", line 33, in _argmax_area
    + y_bucket * (avg_next_x - prev_x)
TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```
I have the problem because I cannot use lttbc - maybe because I work on a Debian under WSL. I works fine on a native linux.
If you think it's possible to fix that, it would be great.
Should I open a dedicated issue ?

Cheers,

**Comment by jonasvdd** [comment] 2023-03-28 08:28
Hi @maxime-jolliet-airseas,

Indeed, this is strange behavior, so you can certainly make an issue for that!
Will try to look into it somewhere later this week! 

As for now, you could for example opt to use the [`MinMax`](https://predict-idlab.github.io/plotly-resampler/aggregation.html#plotly_resampler.aggregation.aggregators.MinMaxAggregator) aggregator! :)
